"""ENGINE v3 ACCEPTANCE (2): touch census over the model's 225 dates.

For each of the 225 ``dates_used`` (NQ_20260602_232808), build the production v3 trade
bars + levels (FULL-prior-day PDH/PDL, per-level availability), and enumerate the
first-touch events under the ENFORCED availability guard. Reports:

  * touch counts by SESSION x LEVEL_TYPE (the v3 touch population),
  * the v3 LOOK-AHEAD count (a kept touch whose bar closes before its level's
    availability) — MUST be 0 by construction of the guard, asserted non-vacuously,
  * the PRE-v3 look-ahead count (same bars+levels, guard OFF) — the touches the guard
    REMOVES (the look-ahead self-touches the [[levels-rth-lookahead-rootcause]] audit
    found were 71% of labels), so the fix is shown to do real work.

No features/labels are computed (this is a touch census, fast). The labeled dataset
itself is regenerated by ``rebuild_v3.py``. Read-only inputs; PYTHONPATH=src.
"""
from __future__ import annotations

import json
import sys
from collections import defaultdict
from datetime import date, timedelta
from pathlib import Path

import pandas as pd

import strategy_core as sc
from strategy_core import build_zones, classify_session, detect_touches

from alpha_lab.agents.data_infra.ml.config import DashboardUtilityConfig
from alpha_lab.agents.data_infra.ml.dashboard_utility_builder import (
    _build_bars_for_date,
    _compute_levels_for_date,
    _ensure_et_index,
)
from alpha_lab.agents.data_infra.ml.engine_decision import (
    TRADE_TICK,
    bars_et_to_engine,
    levels_to_engine,
)

DATA_DIR = Path("C:/Users/gonza/Documents/Claude-Quant-Lab/data/databento")
SYMBOL = "NQ"
OUT = Path(__file__).parent / "census_results.json"
UTIL = DashboardUtilityConfig(
    bar_type="147t", include_approach_features=True, approach_window_minutes=15,
    interaction_window_minutes=5, tp_points=15.0, sl_points=15.0, trap_mfe_min=5.0,
    level_proximity_pts=0.5,
)


def _avail_dates(lo: str, hi: str) -> list[str]:
    out, d, end = [], date.fromisoformat(lo), date.fromisoformat(hi)
    while d <= end:
        if (DATA_DIR / SYMBOL / d.isoformat()).is_dir():
            out.append(d.isoformat())
        d += timedelta(days=1)
    return out


def main() -> int:
    ev = json.load(open("models/NQ_20260602_232808/evaluation.json"))
    target = sorted(ev["dates_used"])
    print(f"engine={sc.ENGINE_VERSION}  target dates={len(target)} "
          f"[{target[0]} .. {target[-1]}]")
    target_set = set(target)
    # FAITHFUL to the rebuild: build_utility_dataset(dates_in_range) carries from None
    # over the sorted dates with NO warm-up (date_range.start == dates_used[0]), so the
    # FIRST date (2025-06-02) has no PDH/PDL — same as the original v2 build. The census
    # mirrors that exactly so its touch population == the regenerated dataset's.
    all_dates = target

    counts: dict[tuple[str, str], int] = defaultdict(int)
    session_totals: dict[str, int] = defaultdict(int)
    leveltype_totals: dict[str, int] = defaultdict(int)
    v3_lookahead = 0
    pre_v3_lookahead = 0
    total_gated = 0
    total_ungated = 0
    n_done = 0
    prev_full_hl = None
    lookahead_examples: list[str] = []

    for ds in all_dates:
        try:
            bars = _build_bars_for_date(DATA_DIR, SYMBOL, ds, UTIL)
        except Exception as e:
            sys.stderr.write(f"FAIL build {ds}: {e}\n")
            continue
        if bars.empty:
            continue
        bars_et = _ensure_et_index(bars)
        new_full = (float(bars_et["high"].max()), float(bars_et["low"].min()))
        levels = _compute_levels_for_date(bars_et, ds, prev_full_hl, None, None)

        if ds in target_set and levels:
            td = date.fromisoformat(ds)
            eng_bars = bars_et_to_engine(bars_et, td, TRADE_TICK)
            zones_av = build_zones(levels_to_engine(levels, with_availability=True))
            avail = {round(z.representative_price, 6): z.available_from for z in zones_av}
            gated = detect_touches(
                eng_bars,
                build_zones(levels_to_engine(levels, with_availability=True)),
                tick_size=TRADE_TICK, trading_day=td,
            )
            ungated = detect_touches(
                eng_bars,
                build_zones(levels_to_engine(levels, with_availability=False)),
                tick_size=TRADE_TICK, trading_day=td,
            )
            for t in gated:
                sess = classify_session(t.bar_ts_utc).session
                counts[(sess, t.level_type)] += 1
                session_totals[sess] += 1
                leveltype_totals[t.level_type] += 1
                A = avail.get(round(t.representative_price, 6))
                if A is not None and t.bar_ts_utc < A:
                    v3_lookahead += 1  # MUST stay 0
            for t in ungated:
                A = avail.get(round(t.representative_price, 6))
                if A is not None and t.bar_ts_utc < A:
                    pre_v3_lookahead += 1
                    if len(lookahead_examples) < 6:
                        et = pd.Timestamp(t.bar_ts_utc).tz_convert("US/Eastern")
                        av = pd.Timestamp(A).tz_convert("US/Eastern")
                        lookahead_examples.append(
                            f"{ds} {t.level_type}: touched {et} < available {av}")
            total_gated += len(gated)
            total_ungated += len(ungated)
            n_done += 1
            if n_done % 25 == 0:
                print(f"  ...{n_done}/{len(target)} dates "
                      f"(gated touches so far={total_gated})", flush=True)

        prev_full_hl = new_full

    # ── report ──────────────────────────────────────────────────────────────
    print()
    print(f"dates processed (with touches) = {n_done}/{len(target)}")
    print(f"v3 gated touches (the dataset population) = {total_gated}")
    print(f"pre-v3 ungated touches (guard OFF)        = {total_ungated}")
    print()
    print("touch counts by SESSION x LEVEL_TYPE (v3, availability-enforced):")
    sessions = sorted(session_totals, key=lambda s: -session_totals[s])
    ltypes = sorted(leveltype_totals, key=lambda s: -leveltype_totals[s])
    header = "  " + f"{'session':10s}" + "".join(f"{lt:>13s}" for lt in ltypes) + f"{'TOTAL':>9s}"
    print(header)
    for s in sessions:
        row = "  " + f"{s:10s}" + "".join(f"{counts.get((s, lt), 0):13d}" for lt in ltypes)
        row += f"{session_totals[s]:9d}"
        print(row)
    tot_row = "  " + f"{'TOTAL':10s}" + "".join(f"{leveltype_totals[lt]:13d}" for lt in ltypes)
    tot_row += f"{total_gated:9d}"
    print(tot_row)
    print()
    print(f"*** v3 LOOK-AHEAD count (kept touch before its level availability) = "
          f"{v3_lookahead}  (MUST be 0)")
    print(f"    pre-v3 look-ahead REMOVED by the guard = {pre_v3_lookahead} "
          f"({(100.0 * pre_v3_lookahead / total_ungated) if total_ungated else 0:.1f}% "
          f"of pre-v3 touches)")
    for ex in lookahead_examples:
        print(f"      e.g. {ex}")
    print()
    print("CENSUS", "PASS" if v3_lookahead == 0 else "FAIL")

    OUT.write_text(json.dumps({
        "engine_version": sc.ENGINE_VERSION,
        "n_target_dates": len(target),
        "n_dates_with_touches": n_done,
        "total_gated_touches": total_gated,
        "total_ungated_touches": total_ungated,
        "v3_lookahead_count": v3_lookahead,
        "pre_v3_lookahead_count": pre_v3_lookahead,
        "counts_by_session_level": {f"{s}|{lt}": n for (s, lt), n in sorted(counts.items())},
        "session_totals": dict(session_totals),
        "leveltype_totals": dict(leveltype_totals),
        "lookahead_examples": lookahead_examples,
    }, indent=2, default=str))
    print(f"wrote {OUT}")
    return 0 if v3_lookahead == 0 else 2


if __name__ == "__main__":
    sys.exit(main())
