"""Exact bindings and calendar evidence for a completed comparison's review folder.

Built from the frozen plan and its verified strategy study (never from ledger
history or display labels):

* :func:`configuration_bindings` — per configuration, the configurator inputs
  (every axis value), the fully resolved effective strategy section and its
  identity (re-resolved now and required to equal the frozen plan), the size,
  cost and exit rule, and which equivalence population its no-account replay
  belongs to; plus the exact study-package and Strategy-Core source binding.
* :func:`trading_calendar_rows` — the saved trading-day schedule the run used
  (start, mandatory flat deadline, scheduled close, next reopen) in Chicago time.
* :func:`trade_boundary_check` — every funded trade against that schedule:
  entered and closed inside its own trading day, never across a deadline,
  closed market or weekend; midnight crossings are counted, not forbidden.

The schedule is the verified study's own; it is not independently checked here
against an exchange holiday and shortened-session calendar.
"""

from __future__ import annotations

from typing import Any

import pandas as pd

from alpha_lab.propsim.funded.campaign import TradingDay, display_time, machine_time

__all__ = [
    "EQUIVALENCE_POPULATIONS",
    "configuration_bindings",
    "trade_boundary_check",
    "trading_calendar_rows",
]

EQUIVALENCE_POPULATIONS = {
    True: "saved historical control: the no-account replay equals the verified study's "
          "saved trades",
    False: "generated by the research Strategy-Core: the no-account replay equals Strategy-"
           "Core's own normal day-by-day replay of the same days (an integration check, not "
           "independent evidence that the new exit rule is correct)",
}


def _ns(text: str) -> int:
    return int(pd.Timestamp(text).value)


def configuration_bindings(plan: Any, source: Any, *, plan_id: str) -> dict[str, Any]:
    """Full effective configuration and exact source binding per configuration."""

    from alpha_lab.propsim.funded.comparison_source import resolve_configuration

    rows = []
    variants = getattr(plan, "variants", None)
    if variants is None:  # a version-1 plan: study configurations at one size
        variants = [{"name": c.name, "display_name": c.display_name,
                     "axis_value_ids": tuple(dict(c.axis_value_ids).items()),
                     "resolved_section_config_hash": c.resolved_section_config_hash,
                     "exit_policy": "fixed_target_v1", "instrument": plan.instrument,
                     "quantity": plan.quantity,
                     "cost_per_contract_mills": plan.cost_per_side_cents * 10,
                     "in_verified_study": True, "cache_configuration": c.name}
                    for c in plan.configurations]
    for v in variants:
        v = v if isinstance(v, dict) else v.model_dump()
        ids = dict(v["axis_value_ids"])
        section, cfg = resolve_configuration(ids)
        rows.append({
            "configuration": v["name"],
            "configuration_label": v["display_name"],
            "equivalence_population": EQUIVALENCE_POPULATIONS[bool(v["in_verified_study"])],
            "in_verified_study": bool(v["in_verified_study"]),
            "day_inputs_read_from_configuration": v["cache_configuration"],
            "axis_value_ids": ids,
            "resolved_section_config_hash": v["resolved_section_config_hash"],
            "re_resolved_now_to_the_same_hash":
                cfg.profile_hash == v["resolved_section_config_hash"],
            "effective_section": section.model_dump(mode="json"),
            "exit_policy": v["exit_policy"],
            "instrument": v["instrument"],
            "quantity": v["quantity"],
            "cost_per_contract_per_fill_usd": v["cost_per_contract_mills"] / 1000,
        })
    core = getattr(plan, "core_source", None)
    return {
        "funded_comparison_plan_id": plan_id,
        "strategy_study": plan.source.model_dump(mode="json"),
        "strategy_core_source": (core.model_dump(mode="json") if core is not None else
                                 "the pinned Strategy-Core of the application"),
        "note": ("Each configuration is bound by its configurator inputs and the resolved "
                 "section identity frozen in the plan; the effective section is re-resolved "
                 "through the normal configurator path when this folder is published."),
        "configurations": rows,
    }


def trading_calendar_rows(days: tuple[TradingDay, ...], start_ns: int) -> list[dict[str, Any]]:
    rows = []
    previous = start_ns
    for day in days:
        deadline = display_time(day.deadline_ns)
        rows.append({
            "trading_day": day.trading_day,
            "opens_utc": machine_time(previous), "opens_chicago": display_time(previous),
            "flat_deadline_utc": machine_time(day.deadline_ns),
            "flat_deadline_chicago": deadline,
            "scheduled_close_chicago": display_time(day.day_end_ns),
            "next_reopen_chicago": display_time(day.reopen_ns),
            "shortened_day": "03:55 PM" not in deadline,
        })
        previous = day.reopen_ns
    return rows


def trade_boundary_check(trades: list[dict[str, Any]], days: tuple[TradingDay, ...],
                         start_ns: int) -> dict[str, Any]:
    """Every trade inside its own trading day's window; count midnight crossings."""

    window: dict[str, tuple[int, int]] = {}
    previous = start_ns
    for day in days:
        window[day.trading_day] = (previous, day.deadline_ns)
        previous = day.reopen_ns
    outside, crossing = [], 0
    for t in trades:
        entry, exit_ = _ns(t["entry_utc"]), _ns(t["exit_utc"])
        opened, deadline = window.get(t["trading_day"], (None, None))
        if opened is None or not (opened <= entry <= exit_ <= deadline):
            outside.append({"pair_id": t["pair_id"], "entry_chicago": t["entry_chicago"],
                            "exit_chicago": t["exit_chicago"]})
        chicago = [pd.Timestamp(x, unit="ns", tz="UTC").tz_convert("America/Chicago").date()
                   for x in (entry, exit_)]
        crossing += chicago[0] != chicago[1]
    return {
        "passed": not outside,
        "trades_checked": len(trades),
        "trades_open_past_midnight_inside_one_trading_day": crossing,
        "trades_outside_their_trading_day": outside[:20],
        "trades_outside_their_trading_day_count": len(outside),
        "calendar_basis": "the verified study's saved trading schedule (not independently "
                          "checked against an exchange shortened-session calendar)",
    }
