"""Trade-path evidence, bundles, and capabilities (CS §5.1) — fidelity FIRST.

Historically truthful path evidence for `ifvg_prop_robust_config_search_v1`
R3: a 1-minute bar does not record its intrabar order
(``observed_intrabar_order`` can only be ``"unknown"``); assumed intrabar
paths are SCENARIOS generated by a registered policy (two policies = two
scenario identities and, on order-sensitive trades, two different results);
only actual ordered market/fill evidence supports chronology-sensitive
historical claims. Rule support is CAPABILITY-based — never inferred from an
ordinal fidelity enum — and fails closed with a
:class:`PathCapabilityReport`.

Additive module: the existing evaluation-only propsim API is untouched.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Iterable, Mapping, Sequence
from enum import StrEnum
from typing import ClassVar, Literal

from pydantic import Field

from alpha_lab.agents.data_infra.ifvg.search.identities import (
    SHA256_PATTERN,
    EnvelopeBase,
    FrozenContract,
    ImmutableMap,
    canonical_contract_sha256,
    register_identity_pair,
)

__all__ = [
    "TradePathFidelity",
    "PathCapability",
    "OhlcBarPathObservation",
    "TradePathEvent",
    "TradePathArtifactPayload",
    "TradePathArtifactEnvelope",
    "TradePathBundlePayload",
    "TradePathBundleEnvelope",
    "PropRulePathRequirement",
    "PathCapabilityReport",
    "INTRABAR_SCENARIO_POLICIES",
    "SCENARIO_FIDELITIES",
    "path_event_id",
    "build_closed_trade_artifact",
    "build_ohlc_artifact",
    "build_assumed_intrabar_artifact",
    "build_trade_path_bundle",
    "evaluate_path_capabilities",
]

#: The two registered assumed-intrabar scenario policies. A scenario policy is
#: a FEATURE of the artifact identity: same bar evidence + different policy =
#: different scenario artifact ids and (order-sensitive) different results.
INTRABAR_SCENARIO_POLICIES: tuple[str, ...] = (
    "bar_adverse_extreme_first_v1",
    "bar_favorable_extreme_first_v1",
)


class TradePathFidelity(StrEnum):
    CLOSED_TRADE_ONLY = "closed_trade_only"
    OHLC_1M_UNORDERED = "ohlc_1m_unordered"
    ASSUMED_1M_INTRABAR_PATH = "assumed_1m_intrabar_path"
    ORDERED_MBP1_EVENT_PATH = "ordered_mbp1_event_path"
    ORDERED_FILL_EVENT_PATH = "ordered_fill_event_path"


#: Fidelity classes whose chronology is ASSUMED, not observed. Their evidence
#: can satisfy a rule only as ``scenario_only`` and only when that rule
#: explicitly permits scenario use.
SCENARIO_FIDELITIES: frozenset[TradePathFidelity] = frozenset(
    {TradePathFidelity.ASSUMED_1M_INTRABAR_PATH}
)


class PathCapability(StrEnum):
    CLOSED_TRADE_RESULT = "closed_trade_result"
    REALIZED_PNL_CHRONOLOGY = "realized_pnl_chronology"
    UNREALIZED_MARK_TO_MARKET = "unrealized_mark_to_market"
    MARKET_PRICE_CHRONOLOGY = "market_price_chronology"
    INTRABAR_EXTREMA_ORDER = "intrabar_extrema_order"
    ORDERED_FILLS = "ordered_fills"


#: The honest capability set each fidelity class PROVIDES. Deliberately a
#: mapping, not an ordering: ordered fills do NOT imply market-price
#: chronology, and unordered OHLC provides extrema magnitudes without order.
_FIDELITY_CAPABILITIES: Mapping[TradePathFidelity, frozenset[PathCapability]] = {
    TradePathFidelity.CLOSED_TRADE_ONLY: frozenset(
        {PathCapability.CLOSED_TRADE_RESULT, PathCapability.REALIZED_PNL_CHRONOLOGY}
    ),
    TradePathFidelity.OHLC_1M_UNORDERED: frozenset(
        {
            PathCapability.CLOSED_TRADE_RESULT,
            PathCapability.REALIZED_PNL_CHRONOLOGY,
            PathCapability.UNREALIZED_MARK_TO_MARKET,
        }
    ),
    TradePathFidelity.ASSUMED_1M_INTRABAR_PATH: frozenset(
        {
            PathCapability.CLOSED_TRADE_RESULT,
            PathCapability.REALIZED_PNL_CHRONOLOGY,
            PathCapability.UNREALIZED_MARK_TO_MARKET,
            PathCapability.INTRABAR_EXTREMA_ORDER,
            PathCapability.MARKET_PRICE_CHRONOLOGY,
        }
    ),
    TradePathFidelity.ORDERED_MBP1_EVENT_PATH: frozenset(
        {
            PathCapability.CLOSED_TRADE_RESULT,
            PathCapability.REALIZED_PNL_CHRONOLOGY,
            PathCapability.UNREALIZED_MARK_TO_MARKET,
            PathCapability.INTRABAR_EXTREMA_ORDER,
            PathCapability.MARKET_PRICE_CHRONOLOGY,
        }
    ),
    TradePathFidelity.ORDERED_FILL_EVENT_PATH: frozenset(
        {
            PathCapability.CLOSED_TRADE_RESULT,
            PathCapability.REALIZED_PNL_CHRONOLOGY,
            PathCapability.ORDERED_FILLS,
        }
    ),
}


class OhlcBarPathObservation(FrozenContract):
    """Honest raw 1-minute evidence: the intrabar order is NOT recorded."""

    open_ts_utc: str
    close_ts_utc: str
    open_price: float
    high_price: float
    low_price: float
    close_price: float
    observed_intrabar_order: Literal["unknown"] = "unknown"


class TradePathEvent(FrozenContract):
    event_id: str = Field(pattern=SHA256_PATTERN)
    event_ts_utc: str
    event_ordinal: int = Field(ge=0)
    source_order_key: tuple[str, str, int, int] | None
    kind: Literal["bar_extreme", "bar_close", "quote", "trade", "fill", "entry", "exit"]
    price: float
    quantity: float | None
    generating_policy_id: str | None


def path_event_id(
    *,
    trade_id: str,
    event_ordinal: int,
    kind: str,
    event_ts_utc: str,
    price: float,
    generating_policy_id: str | None,
) -> str:
    """Exact, deterministic path-event id (content-derived, never positional)."""

    return hashlib.sha256(
        json.dumps(
            {
                "trade_id": trade_id,
                "event_ordinal": event_ordinal,
                "kind": kind,
                "event_ts_utc": event_ts_utc,
                "price": price,
                "generating_policy_id": generating_policy_id,
            },
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
    ).hexdigest()


class TradePathArtifactPayload(FrozenContract):
    core_replay_id: str = Field(pattern=SHA256_PATTERN)
    trade_id: str
    fidelity: TradePathFidelity
    capabilities: tuple[PathCapability, ...]
    observations: tuple[OhlcBarPathObservation, ...] | None
    ordered_events: tuple[TradePathEvent, ...] | None
    intrabar_scenario_policy_id: str | None
    source_identities: tuple[str, ...]


class TradePathArtifactEnvelope(EnvelopeBase):
    _ID_FIELD: ClassVar[str] = "trade_path_artifact_id"

    trade_path_artifact_id: str = Field(pattern=SHA256_PATTERN)
    payload: TradePathArtifactPayload
    manifest_payload_sha256: str = Field(pattern=SHA256_PATTERN)


class TradePathBundlePayload(FrozenContract):
    core_replay_id: str = Field(pattern=SHA256_PATTERN)
    gross_trade_stream_hash: str = Field(pattern=SHA256_PATTERN)
    ordered_trade_ids: tuple[str, ...]
    ordered_trade_path_artifact_ids: tuple[str, ...]
    bundle_capabilities: tuple[PathCapability, ...]
    per_trade_capability_report_ids: tuple[str, ...]
    coverage_policy_id: str


class TradePathBundleEnvelope(EnvelopeBase):
    _ID_FIELD: ClassVar[str] = "trade_path_bundle_id"

    trade_path_bundle_id: str = Field(pattern=SHA256_PATTERN)
    payload: TradePathBundlePayload
    manifest_payload_sha256: str = Field(pattern=SHA256_PATTERN)


class PropRulePathRequirement(FrozenContract):
    rule_id: str
    required_path_capabilities: tuple[PathCapability, ...]
    accepted_fidelity_classes: tuple[TradePathFidelity, ...]
    scenario_use_permitted: bool


class PathCapabilityReport(FrozenContract):
    trade_path_bundle_id: str = Field(pattern=SHA256_PATTERN)
    available_capabilities: tuple[PathCapability, ...]
    per_rule: ImmutableMap[str, Literal["supported", "scenario_only", "unsupported"]]
    failure_reasons: ImmutableMap[str, tuple[str, ...]]


def _sorted_caps(caps: Iterable[PathCapability]) -> tuple[PathCapability, ...]:
    return tuple(sorted(caps, key=lambda c: c.value))


def _capabilities_for(fidelity: TradePathFidelity) -> frozenset[PathCapability]:
    return _FIDELITY_CAPABILITIES[fidelity]


def _artifact_envelope(payload: TradePathArtifactPayload) -> TradePathArtifactEnvelope:
    # NOTE (honest provenance): no artifact store exists in R3, so
    # manifest_payload_sha256 is a DERIVED PLACEHOLDER (a pure function of the
    # payload id) — it attests no materialized bytes and adds no provenance
    # beyond the id until a store mints real manifests (R4/R5 wiring).
    return TradePathArtifactEnvelope(
        trade_path_artifact_id=canonical_contract_sha256(payload),
        payload=payload,
        manifest_payload_sha256=canonical_contract_sha256(
            {"manifest_for": canonical_contract_sha256(payload)}
        ),
    )


def build_closed_trade_artifact(
    *,
    core_replay_id: str,
    trade_id: str,
    entry_ts_utc: str,
    resolution_ts_utc: str,
    entry_price: float,
    exit_price: float,
    quantity: float = 1.0,
    source_identities: tuple[str, ...] = (),
) -> TradePathArtifactEnvelope:
    """The base fidelity: an entry and an exit, nothing assumed in between."""

    events = []
    for ordinal, (kind, ts, price) in enumerate(
        (("entry", entry_ts_utc, entry_price), ("exit", resolution_ts_utc, exit_price))
    ):
        events.append(
            TradePathEvent(
                event_id=path_event_id(
                    trade_id=trade_id,
                    event_ordinal=ordinal,
                    kind=kind,
                    event_ts_utc=ts,
                    price=price,
                    generating_policy_id=None,
                ),
                event_ts_utc=ts,
                event_ordinal=ordinal,
                source_order_key=None,
                kind=kind,  # type: ignore[arg-type]
                price=price,
                quantity=quantity,
                generating_policy_id=None,
            )
        )
    payload = TradePathArtifactPayload(
        core_replay_id=core_replay_id,
        trade_id=trade_id,
        fidelity=TradePathFidelity.CLOSED_TRADE_ONLY,
        capabilities=_sorted_caps(
            _capabilities_for(TradePathFidelity.CLOSED_TRADE_ONLY)
        ),
        observations=None,
        ordered_events=tuple(events),
        intrabar_scenario_policy_id=None,
        source_identities=source_identities,
    )
    return _artifact_envelope(payload)


def build_ohlc_artifact(
    *,
    core_replay_id: str,
    trade_id: str,
    observations: Sequence[OhlcBarPathObservation],
    source_identities: tuple[str, ...] = (),
) -> TradePathArtifactEnvelope:
    """Honest unordered 1-minute evidence: extremes without chronology."""

    if not observations:
        raise ValueError("an OHLC path artifact requires at least one bar observation")
    payload = TradePathArtifactPayload(
        core_replay_id=core_replay_id,
        trade_id=trade_id,
        fidelity=TradePathFidelity.OHLC_1M_UNORDERED,
        capabilities=_sorted_caps(
            _capabilities_for(TradePathFidelity.OHLC_1M_UNORDERED)
        ),
        observations=tuple(observations),
        ordered_events=None,
        intrabar_scenario_policy_id=None,
        source_identities=source_identities,
    )
    return _artifact_envelope(payload)


def build_assumed_intrabar_artifact(
    *,
    core_replay_id: str,
    trade_id: str,
    trade_direction: Literal["long", "short"],
    observations: Sequence[OhlcBarPathObservation],
    scenario_policy_id: str,
    source_identities: tuple[str, ...] = (),
) -> TradePathArtifactEnvelope:
    """A SCENARIO: the registered policy assumes the intrabar extreme order.

    "Adverse" is POSITION-adverse (the bar low for a long, the bar high for a
    short — the same semantics the account walk applies to MAE-first
    traversal): ``bar_adverse_extreme_first_v1`` visits each bar's adverse
    extreme first (the conservative approximation);
    ``bar_favorable_extreme_first_v1`` the favorable extreme first. Two
    policies produce two different ordered event streams and therefore two
    different scenario artifact identities — and, on order-sensitive trades,
    two different simulated results.
    """

    if scenario_policy_id not in INTRABAR_SCENARIO_POLICIES:
        raise ValueError(
            f"unregistered intrabar scenario policy {scenario_policy_id!r}; "
            f"registered: {INTRABAR_SCENARIO_POLICIES}"
        )
    if not observations:
        raise ValueError("a scenario artifact requires at least one bar observation")
    events: list[TradePathEvent] = []
    ordinal = 0

    def _emit(kind: str, ts: str, price: float) -> None:
        nonlocal ordinal
        events.append(
            TradePathEvent(
                event_id=path_event_id(
                    trade_id=trade_id,
                    event_ordinal=ordinal,
                    kind=kind,
                    event_ts_utc=ts,
                    price=price,
                    generating_policy_id=scenario_policy_id,
                ),
                event_ts_utc=ts,
                event_ordinal=ordinal,
                source_order_key=None,
                kind=kind,  # type: ignore[arg-type]
                price=price,
                quantity=None,
                generating_policy_id=scenario_policy_id,
            )
        )
        ordinal += 1

    adverse_first = scenario_policy_id == "bar_adverse_extreme_first_v1"
    for bar in observations:
        # position-adverse extreme: against the trade's direction (matches
        # the account walk's MAE-first semantics under the same policy id)
        adverse = bar.low_price if trade_direction == "long" else bar.high_price
        favorable = bar.high_price if trade_direction == "long" else bar.low_price
        first, second = (
            (adverse, favorable) if adverse_first else (favorable, adverse)
        )
        _emit("bar_extreme", bar.open_ts_utc, first)
        _emit("bar_extreme", bar.open_ts_utc, second)
        _emit("bar_close", bar.close_ts_utc, bar.close_price)

    payload = TradePathArtifactPayload(
        core_replay_id=core_replay_id,
        trade_id=trade_id,
        fidelity=TradePathFidelity.ASSUMED_1M_INTRABAR_PATH,
        capabilities=_sorted_caps(
            _capabilities_for(TradePathFidelity.ASSUMED_1M_INTRABAR_PATH)
        ),
        observations=tuple(observations),
        ordered_events=tuple(events),
        intrabar_scenario_policy_id=scenario_policy_id,
        source_identities=source_identities,
    )
    return _artifact_envelope(payload)


def build_trade_path_bundle(
    artifacts: Sequence[TradePathArtifactEnvelope],
    *,
    gross_trade_stream_hash: str,
    ordered_trade_ids: Sequence[str],
    coverage_policy_id: str = "every_executed_trade_exactly_once_v1",
    per_trade_capability_report_ids: tuple[str, ...] = (),
) -> TradePathBundleEnvelope:
    """The complete strategy path evidence: every trade, exactly one artifact.

    ``ordered_trade_ids`` is the executed-trade order from the gross stream;
    a missing or duplicated artifact fails closed. ``bundle_capabilities`` is
    the intersection of every included artifact's capabilities.
    """

    if not artifacts:
        raise ValueError(
            "a trade-path bundle requires at least one artifact — an empty "
            "bundle cannot honestly claim any core replay"
        )
    by_trade: dict[str, TradePathArtifactEnvelope] = {}
    for artifact in artifacts:
        trade_id = artifact.payload.trade_id
        if trade_id in by_trade:
            raise ValueError(f"trade {trade_id!r} has more than one path artifact")
        by_trade[trade_id] = artifact
    missing = [trade_id for trade_id in ordered_trade_ids if trade_id not in by_trade]
    if missing:
        raise ValueError(f"trades without a path artifact: {missing}")
    extra = sorted(set(by_trade) - set(ordered_trade_ids))
    if extra:
        raise ValueError(f"path artifacts for unknown trades: {extra}")
    core_ids = {artifact.payload.core_replay_id for artifact in artifacts}
    if len(core_ids) > 1:
        raise ValueError("a bundle may only cover ONE core replay")
    capabilities: set[PathCapability] | None = None
    for artifact in artifacts:
        caps = set(artifact.payload.capabilities)
        capabilities = caps if capabilities is None else (capabilities & caps)
    payload = TradePathBundlePayload(
        core_replay_id=next(iter(core_ids)),
        gross_trade_stream_hash=gross_trade_stream_hash,
        ordered_trade_ids=tuple(ordered_trade_ids),
        ordered_trade_path_artifact_ids=tuple(
            by_trade[trade_id].trade_path_artifact_id for trade_id in ordered_trade_ids
        ),
        bundle_capabilities=_sorted_caps(capabilities or set()),
        per_trade_capability_report_ids=per_trade_capability_report_ids,
        coverage_policy_id=coverage_policy_id,
    )
    return TradePathBundleEnvelope(
        trade_path_bundle_id=canonical_contract_sha256(payload),
        payload=payload,
        manifest_payload_sha256=canonical_contract_sha256(
            {"manifest_for": canonical_contract_sha256(payload)}
        ),
    )


def evaluate_path_capabilities(
    bundle: TradePathBundleEnvelope,
    requirements: Sequence[PropRulePathRequirement],
    *,
    artifacts: Sequence[TradePathArtifactEnvelope],
) -> PathCapabilityReport:
    """PER-TRADE rule support from EXPLICIT capabilities + accepted classes.

    Fidelities are DERIVED from the bundle's own artifacts (never a
    caller-asserted side channel). A rule is ``supported`` only when its
    required capability set is available on the whole bundle AND EVERY
    covered trade's artifact carries an accepted, non-scenario fidelity
    class; it is ``scenario_only`` when every trade is satisfiable but at
    least one only through an assumed scenario class the rule explicitly
    permits; otherwise ``unsupported`` with exact per-trade reasons. Support
    is never inferred from enum ordering, and a single trade whose only
    evidence is unacceptable fails the whole stream (fail-closed).
    """

    by_id = {artifact.trade_path_artifact_id: artifact for artifact in artifacts}
    ordered = bundle.payload.ordered_trade_path_artifact_ids
    missing_artifacts = [artifact_id for artifact_id in ordered if artifact_id not in by_id]
    if missing_artifacts:
        raise ValueError(
            "capability evaluation requires every bundle artifact; missing: "
            f"{[artifact_id[:12] for artifact_id in missing_artifacts]}"
        )
    per_trade: tuple[tuple[str, TradePathFidelity], ...] = tuple(
        (by_id[artifact_id].payload.trade_id, by_id[artifact_id].payload.fidelity)
        for artifact_id in ordered
    )
    available = set(bundle.payload.bundle_capabilities)
    per_rule: dict[str, str] = {}
    reasons: dict[str, tuple[str, ...]] = {}
    for requirement in requirements:
        rule_reasons: list[str] = []
        missing = sorted(
            cap.value
            for cap in requirement.required_path_capabilities
            if cap not in available
        )
        if missing:
            rule_reasons.append(f"missing capabilities: {missing}")
        accepted = set(requirement.accepted_fidelity_classes)
        unacceptable = [
            trade_id for trade_id, fidelity in per_trade if fidelity not in accepted
        ]
        if unacceptable:
            rule_reasons.append(
                "trade(s) without an accepted fidelity class: "
                f"{sorted(unacceptable)}"
            )
        scenario_trades = [
            trade_id
            for trade_id, fidelity in per_trade
            if fidelity in accepted and fidelity in SCENARIO_FIDELITIES
        ]
        if not rule_reasons and scenario_trades and not requirement.scenario_use_permitted:
            rule_reasons.append(
                "trade(s) whose only accepted evidence is an assumed scenario "
                f"and the rule does not permit scenario use: {sorted(scenario_trades)}"
            )
        if rule_reasons:
            per_rule[requirement.rule_id] = "unsupported"
            reasons[requirement.rule_id] = tuple(rule_reasons)
            continue
        per_rule[requirement.rule_id] = (
            "scenario_only" if scenario_trades else "supported"
        )
    return PathCapabilityReport(
        trade_path_bundle_id=bundle.trade_path_bundle_id,
        available_capabilities=_sorted_caps(available),
        per_rule=per_rule,
        failure_reasons=reasons,
    )


def _example_artifact_payload() -> TradePathArtifactPayload:
    return build_closed_trade_artifact(
        core_replay_id="a" * 64,
        trade_id="trade-001",
        entry_ts_utc="2026-01-13T14:00:00+00:00",
        resolution_ts_utc="2026-01-13T14:05:00+00:00",
        entry_price=20000.0,
        exit_price=20010.0,
    ).payload


def _example_bundle_payload() -> TradePathBundlePayload:
    artifact = build_closed_trade_artifact(
        core_replay_id="a" * 64,
        trade_id="trade-001",
        entry_ts_utc="2026-01-13T14:00:00+00:00",
        resolution_ts_utc="2026-01-13T14:05:00+00:00",
        entry_price=20000.0,
        exit_price=20010.0,
    )
    return build_trade_path_bundle(
        (artifact,),
        gross_trade_stream_hash="b" * 64,
        ordered_trade_ids=("trade-001",),
    ).payload


register_identity_pair(
    name="TradePathArtifact",
    envelope_cls=TradePathArtifactEnvelope,
    payload_cls=TradePathArtifactPayload,
    id_field="trade_path_artifact_id",
    example_factory=_example_artifact_payload,
    extra_envelope_fields=("manifest_payload_sha256",),
)
register_identity_pair(
    name="TradePathBundle",
    envelope_cls=TradePathBundleEnvelope,
    payload_cls=TradePathBundlePayload,
    id_field="trade_path_bundle_id",
    example_factory=_example_bundle_payload,
    extra_envelope_fields=("manifest_payload_sha256",),
)
